- file:
    path: /vagrant/shop
    owner: "{{ shop.web_user }}"
    mode: 0644

#- file:
#    path: /vagrant/shop/www/source
#    state: absent

#- file:
#    path: /vagrant/shop/www/vendor
#    state: absent


- file:
    path: /vagrant/shop/www
    owner: "{{ shop.web_user }}"
    mode: 0644

- file:
    path: /var/www
    owner: "{{ shop.web_user }}"
    mode: 0644

# cd /shop
# composer create-project --no-dev oxid-esales/oxideshop-project www dev-b-6.0-ce
# will create the folder /vagrant/shop/www with subfolders: /vendor and /source
# so document Root has to point to /vagrant/shop/www/source
- composer:
     command: create-project
     arguments: --no-dev oxid-esales/oxideshop-project www dev-b-6.0-ce
     working_dir: /vagrant/shop
     prefer_dist: yes
  become: yes
  become_user: "{{ shop.web_user }}"