---
galaxy_info:
  author: Martin Micunda
  description: Install the latest stable version of bower.
  license: MIT
  min_ansible_version: 1.7
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - development
  - web

dependencies:
#  - src: martinmicunda.nodejs
#    name: nodejs
