---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- shell: hostname
  register: current_hostname

- name: mysql | Install MySQL Packages
  become: yes
  become_method:
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: mysql | Update root password for all root accounts
  mysql_user: name=root host={{ item }} check_implicit_admin=yes password={{ mysql.root_password }} login_user=root login_password={{ mysql.root_password }}
  with_items:
    - "{{ current_hostname.stdout | lower }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: mysql | Create databases
  mysql_db:
    name: "{{ item }}"
    state: present
    login_user: root
    login_password: "{{ mysql.root_password }}"
    encoding: utf8
    collation: utf8_general_ci
  with_items: "{{ mysql.databases }}"

#- name: mysql | Import dump
#  mysql_db: name={{ mysql.database }} state=import login_user=root login_password={{ mysql.root_password }} target=/vagrant/{{ mysql.dump }}
#  when: mysql.dump

- name: mysql | Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent login_user=root login_password={{ mysql.root_password }}
  with_items:
    - localhost
    - "{{ current_hostname.stdout | lower }}"

- name: mysql | Create users for each database user_<db_name>
  mysql_user: name={{ mysql.user }}_{{ item }} password={{ mysql.password }} priv={{ item }}.*:ALL state=present login_user=root login_password={{ mysql.root_password }}
  with_items: "{{ mysql.databases }}"

- name: Set some MYSQL Variables
  mysql_variables:
     config_file: "/etc/mysql/my.cnf"
     variable: sql_mode
     value: 'IGNORE_SPACE,NO_AUTO_CREATE_USER,ALLOW_INVALID_DATES'
     login_user: root
     login_password: "{{ mysql.root_password }}"



