---
server:
    install: '1'
    packages: [vim, git, imagemagick, nodejs, npm]
    timezone: Europe/Berlin
    locale: de_DE.UTF-8

vagrant_local:
    install: '1'
    vm: { base_box: xenial64, hostname: oxidshop.local, ip: 192.168.33.99, memory: '2048', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }

# more stettings see ansible role nginx -> defaults -> main.yml
nginx:
    install: '0'
    docroot: /vagrant/shop/www/source
    servername: oxidshop.local

# more stettings see ansible role apache -> defaults -> main.yml
apache:
    install: '1'

mysql:
    install: '1'
    root_password: '123'
    databases: [shop]
    user: user
    password: password

php:
    php_ppa: "ppa:ondrej/php"
    php_packages:
      - php7.0-common
      - php7.0-cli
      - php7.0-intl
      - php7.0-curl
      - php7.0-cgi
      - php7.0-fpm
      - php7.0-mysql
      - php7.0-gd
      - php7.0-mcrypt
      - php7.0-mbstring
      - php7.0-imagick
      - php7.0-soap
      - php7.0-zip
      - php7.0-xml
      - php7.0-bcmath

    php_timezone: Europe/Berlin

    php_allow_url_fopen: 1
    php_upload_max_filesize: "20M"
    php_post_max_size: "20M"
    php_memory_limit: "1024M"
    php_max_execution_time: 240

    php_opcache_enable: 1
    php_opcache_revalidate_freq: 2592000
    php_opcache_opcache_validate_timestamps: 1
    php_opcache_max_accelerated_files: 20000
    php_opcache_memory_consumption: 192
    php_opcache_interned_strings_buffer: 16
    php_opcache_fast_shutdown: 1
    max_input_vars: 2000



composer:
    install: '1'

typo3:
    install: False
    get_url: https://get.typo3.org/
    sources_path: /vagrant/shop_src
    # XXX change connect  site Name of your Server
    connect:
      version: "8.7.6"
      deploy_shared_directories:
        - "fileadmin"
        - "uploads"

      # Check if the following directories exist and are writable
      deploy_writeable_directories:
        - "typo3temp"
      deploy_source_directories:
        - "typo3"
        - "vendor"

shop:
   install: True
   web_user: 'www-data'
   get_url: https://get.typo3.org/
   sources_path: /vagrant/shop_src
   version: ""
   #deploy_shared_directories:
   #   - "fileadmin"
   #   - "uploads"

   # Check if the following directories exist and are writable
   #deploy_writeable_directories:
   #   - "tmp"
   deploy_source_directories:
      - "source"
      - "vendor"
