---

- name: Installing packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - "{{ apache2_package }}"
  #  - "{{ apache2_mpm_package }}"
  #  - "libapache2-mod-php5.6"

- name: Adding rules
  copy:
    src: "{{ item }}/"
    dest: "/{{ item }}/"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - etc/apache2/rules
