---

- name: Enabling modules ( see default.yaml   -> apache2_modules
  command: >
    a2enmod {{ item.id }}
  args:
    creates: "/etc/apache2/mods-enabled/{{ item.id }}.load"
  when: item.state is not defined or item.state != 'absent'
  with_items: "{{ apache2_modules }}"
  notify: reload apache2

- name: Disabling modules
  command: >
    a2dismod {{ item.id }}
  args:
    removes: "/etc/apache2/mods-enabled/{{ item.id }}.load"
  when: item.state is defined and item.state == 'absent'
  with_items: "{{ apache2_modules }}"
  notify: reload apache2
