---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Install git
      apt: pkg=git

  vars_files:
    - vars/all.yml
  roles:
     - server
     - vagrant_local

     - create-ssl-files
     - franklinkim.apache2
     - mysql
     - ansible-role-bower
     - ansible-role-php5.6
     - ansible-role-daemonize
     - ansible-role-mailhog
     - composer
# This installs an empty OXID Shop V4 .. before this, adds id files to root path of the vagrant maschine
     - zz-final-task
     - oxidshopV4
