galaxy_info:
  author: Benjamin Mack
  description: A role for deploying projects of the PHP-based Enterprise CMS TYPO3
  company: b13
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - all
  - name: Fedora
    versions:
    - all
  #- name: Windows
  #  versions:
  #  - all
  #  - 2012R2
  - name: opensuse
    versions:
    - all
  - name: Amazon
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: SLES
    versions:
    - all
  - name: GenericLinux
    versions:
    - all
  - name: Debian
    versions:
    - all

  galaxy_tags:
    - deployment
    - deploy
    - TYPO3
    - CMS
    - PHP
    - Composer
